language: generic 

sudo: required
services:
    - docker


before_install:
    - docker build -t talyoffe/docker-react -f Dockerfile.dev .


script:
    - docker run -e CI=true talyoffe/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-en"
  bucket_name: "elasticbeanstalk-us-west-2-022585997406"
  bucket_path: "docker-react"
  on:
    branch: master